export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_AUTH = 'FETCH_USER_AUTH'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'
export const ADD_SUM = 'ADD_SUM'

export const CONSUM = 'CONSUM'
export const RECEIP = 'RECEIP'

export const FETCH_OPERATIONS = 'FETCH_OPERATIONS'
export const FETCH_OPERATIONS_SUCCESS = 'FETCH_OPERATIONS_SUCCESS'
export const FETCH_OPERATIONS_ERROR = 'FETCH_OPERATIONS_ERROR'
export const SEND_OPERATION = 'SEND_OPERATION'